apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: expense
  labels: 
    app: mysql
    tier: db
    project: expense 
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: mysql 
      tier: db
      project: expense
  template: 
    metadata: 
      labels: 
        app: mysql 
        tier: db 
        project: expense 
    spec: 
      containers: 
      - name: mysql
        image: amarnath235/mysql:{{ .Values.deployment.imageVersion }}
---
apiVersion: v1 
kind: Service
metadata: 
  name: mysql 
  namespace: expense 
spec:
  selector: 
    project: expense
    app: mysql 
    tier: db
  ports: 
  - name: mysql-port
    protocol: TCP
    port: 3306 # Service Port
    targetPort: 3306  # Container Port